name: ligo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy<2.0
  - scipy
  - matplotlib
  - h5py
  - pandas
  - requests
  - ipykernel
  - jupyterlab
  - notebook
  - pip
